### ISSUE TITLE
Request: Global shapefiles of the underlying hexgrid

### ISSUE THREAD

**Issue by ahalota** [uber/h3#89] opened 2018-07-06 17:58 UTC
Does anyone know where I can find a set of shapefiles displaying the underlying hex grids used by this library for each level?

**Comment by nrabinowitz** [comment] 2018-07-06 18:02
Closing as a duplicate of #87 - please see the discussion there. Shapefiles would be prohibitively large for all but the coarsest resolutions. See [this StackOverflow question](https://stackoverflow.com/questions/51159241/how-to-generate-shapefiles-for-h3-hexagons-in-a-particular-area) for a method to create Shapefiles yourself for your area of interest.

**Closed by nrabinowitz** 2018-07-06 18:02 UTC

**Comment by ahalota** [comment] 2018-07-06 18:04
Ah, yup, didn't even think to look at closed issues. Thanks!

**Comment by justinelliotmeyers** [comment] 2018-09-12 22:37
could anyone share these?
