### ISSUE TITLE
Added C# binding

### ISSUE THREAD

**Issue by ArnaudSwail** [uber/h3#154] opened 2018-10-18 11:27 UTC
Hi,

I've made a C# binding Standard library based on the 3.2.0 version of the H3 library.
It is available here: https://github.com/entrepreneur-interet-general/H3.Standard

A related nuget package has been released:
PM> Install-Package H3 -Version 3.2.0-alpha.

**Comment by nrabinowitz** [comment] 2018-10-18 18:10
Cool, thank you! Closing this as a dupe of the pull request #155.

**Closed by nrabinowitz** 2018-10-18 18:10 UTC
