### ISSUE TITLE
Unexpected cell boundaries at resolution 7

### ISSUE THREAD

**Issue by billyauhk** [uber/h3#212] opened 2019-03-27 07:34 UTC
Found three strange cells and just verify these with ./h3ToGeoBoundary
Both cells are in Southern Atlantic and numerical error is suspected? All of them involve -52.010831568 10.356241923 which is way off from the intended resolution 7 size.

87dc6d364ffffff
{
   -52.013053368 -34.623293134
   -52.004115638 -34.609673316
   -51.992961023 -34.616515715
   -51.990741057 -34.636968000
   -51.999673873 -34.650589653
   -52.010831568 10.356241923
}

87dc6dacaffffff
{
   -52.033151282 -34.630078657
   -52.024211685 -34.616448895
   -52.013053368 -34.623293134
   -52.010831568 10.356241923
   -52.019766250 -34.657388784
   -52.030927647 -34.650554494
}

87dc6dacbffffff
{
   -52.019766250 -34.657388784
   -52.010831568 10.356241923
   -51.999673873 -34.650589653
   -51.997447785 -34.671043766
   -52.006377553 -34.684677180
   -52.017538323 -34.677854666
}

**Comment by nrabinowitz** [comment] 2019-03-27 15:55
Thanks for the report! Confirmed in C core and JS. It looks like the bad vertex is also shared with children at res 8, e.g. `87dc6dacaffffff`, `88dc6daca3fffff`, etc., so this is not limited to Class III resolutions.

**Comment by nrabinowitz** [comment] 2019-03-27 16:02
It looks like the bad vertex is shared - so e.g. `88dc6dacb5fffff`, `87dc6dacaffffff`, and `87dc6dacbffffff` all share one incorrect vertex. The error seems to be longitude only, at least in these cases.

**Comment by isaacbrodsky** [comment] 2019-03-27 17:00
It looks like this might be a bug in `_geoAzDistanceRads ` around line 252 https://github.com/uber/h3/blob/f9be0f9ffca923f50b96869188fcf0903c36b338/src/h3lib/lib/geoCoord.c#L252 For the vertex with the issue it hits that branch, for other vertices for the index `87dc6d364ffffff` it's not hit. I would assume it should be constraining `coslon` if `coslon > 1.0`.

**Comment by isaacbrodsky** [comment] 2019-03-28 00:36
Thanks @billyauhk for reporting this! The bug should be fixed in the next version of the H3 library released. Please let us know if you see any other unexpected cell vertices.

**Closed by isaacbrodsky** 2019-03-28 00:36 UTC
Labels: bug

**Comment by sahrk** [comment] 2019-04-01 15:01
@billyauhk Thanks from me as well! This was a copy-and-paste from my DGGRID, where the same bug appears to have existed undiscovered for the last 15 years.
